---
title: "Quarter 1- Intership -CIE"
author: "Shitiz Chaudhary"
date: "01.05.2020"
output:
  word_document:
    fig_height: 6
    fig_width: 8tick
  pdf_document: default
  html_document:
    fig_height: 6
    fig_width: 8
---
*Alt + O to fold all chunks*
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
```


*Library*
```{r Library}
# library(olsrr)
library(dplyr)
library(ggplot2)
library(data.table)
library(tidyr)
library(DescTools)
library(tidyverse)
```


```{r}
memory.limit()
memory.limit(size=28000)
```


*Base data files from BTS website*
*Selection of potential Required variables*

```{r}
#base date files from BTS for DB1B -Coupon and DB1B-  Ticket

copq1p1 <- fread("C:/Users/schau/Desktop/Intership/New sample/copon/Origin_and_Destination_Survey_DB1BCoupon_2019_1/Origin_and_Destination_Survey_DB1BCoupon_2019_1.csv", header = T)
copq1p1 <- copq1p1[copq1p1$OriginCountry == "US",]   #check for foreign origin country- zero records in database
copq1p1 <- copq1p1[copq1p1$DestCountry == "US",]    #check for foreign destination country- zero records in database

tikq1p1 <- fread("C:/Users/schau/Desktop/Intership/New sample/ticket/Origin_and_Destination_Survey_DB1BTicket_2019_1/Origin_and_Destination_Survey_DB1BTicket_2019_1.csv", header = T)
tikq1p1 <- tikq1p1[tikq1p1$OriginCountry == "US",]   #check for foreign origin country- zero records in database. Only origin country in ticket

#selection of variables
copq1p2 <- copq1p1[, c( "ItinID"     ,        "MktID"     ,         "SeqNum"           ,  "Coupons", "OriginAirportID", "OriginCityMarketID", "Quarter"    ,        "Origin"   ,          "OriginCountry", "OriginState", "DestAirportID", "DestCityMarketID", "Dest"     ,          "DestCountry", "DestState", "Break"      ,        "CouponType", "OpCarrier" ,"RPCarrier" ,"Passengers", "FareClass"     ,     "Distance"       ,    "DistanceGroup")]

tikq1p2 <- tikq1p1[, c("ItinID" , "Coupons"       ,     "Origin"      ,       "OriginAirportID", "OriginCityMarketID", "OriginCountry", "OriginState", "RoundTrip"      ,    "OnLine"      ,       "DollarCred"     ,    "FarePerMile"    ,    "RPCarrier", "Passengers"  ,       "ItinFare"      ,     "BulkFare"      ,     "Distance"       ,    "DistanceGroup"    ,  "MilesFlown"  )]

rm(copq1p1) #clearing object for memory
rm(tikq1p1) #clearing object for memory
```


*Combined Database for Coupon and Ticket database*

```{r Combine Coupon and Ticket Database}

combinedq1 <- merge(copq1p2,tikq1p2, by  = c("ItinID"))             #combining the two database 

q1 <- combinedq1[, c(1:23, 30:33, 36:37, 40)]           #further removing some variables

rm(copq1p2) #clearing object for memory
rm(tikq1p2) #clearing object for memory
rm(combinedq1) #clearing object for memory
```



*Data Cleaning on combined database*

```{r}

q1 <- q1[q1$ItinFare >= 20, ]            # removing less than $20 tickets 9846816- 9242373 = 604443. 6.14% of total
q1 <- q1[q1$ItinFare <= 9998, ]            # removing greater than $9998 tickets -  169 observations. 9242204 observations remaining

q1 <- q1[q1$BulkFare == 0]           #removing Bulkfare = 1, no observations
q1 <- q1[q1$DollarCred == 1]         #removing Dollarcred = 0, removed 29595 observation. 9212609 observations remaining    

q1[q1$FarePerMile == 0] <- NA        #removing fare per mile = 0 values. No observations found
q1 <- q1[complete.cases(q1$FarePerMile),]


q1 <- q1[q1$Coupons.x  <5,]       #by removing coupons above 4, we had a reduction of 434791 rows, amounting to 4.72% reduction
q1 <- q1[!(q1$RoundTrip == 0 & q1$Coupons.x >2), ] #by removing coupons above 2 for one way trip, we had a reduction of 240165 rows, amounting to 2.74% reduction


#changing and cleaning Fare Class variable 
q1$FareClass <- gsub(".*C.*", "Unrest. Bus", q1$FareClass)
q1$FareClass <- gsub(".*D.*", "Rest. Bus", q1$FareClass)
q1$FareClass <- gsub(".*F.*", "Unrest. 1st", q1$FareClass)
q1$FareClass <- gsub(".*G.*", "Rest. 1st", q1$FareClass)
q1$FareClass <- gsub(".*X.*", "Rest. Econ", q1$FareClass)
q1$FareClass <- gsub(".*Y.*", "Unrest. Econ", q1$FareClass)
q1 <- q1[q1$FareClass != ""]
q1 <- q1[q1$FareClass != "U"]
q1$FareClass <- factor(q1$FareClass, levels = c("Rest. Econ", "Unrest. Econ", "Rest. Bus", "Unrest. Bus", "Rest. 1st", "Unrest. 1st"))

#q1v21 <- fread("C:/Users/schau/Desktop/Intership/June 2021/q1a.csv", header = T)
#q1v21 <- q1


#combining Different classes 
q1$FareClass <- gsub("Rest. Econ|Unrest. Econ", "Economy", q1$FareClass)
q1$FareClass <- gsub("Rest. Bus|Unrest. Bus", "Premium", q1$FareClass)
q1$FareClass <- gsub("Rest. 1st|Unrest. 1st", "First", q1$FareClass)


#column name change
names(q1)[8] <- 'Origin'
names(q1)[13] <- 'Destination'
names(q1)[18] <- 'OperatingCarrier'


#removing First Class
q1$FareClass <- gsub("First", NA, q1$FareClass)
q1 <- q1[complete.cases(q1$FareClass), ] 

names(q1)
#fwrite(q1, file = "q1v1.csv") #remove from final
```




*Sorting by combinations*

```{r}
#rm(q1)

#rm(list=ls())
# q1v1 <- fread("C:/Users/schau/Desktop/Intership/June 2021/q1v1.csv", header = T)
# df1 <- read_csv("q1v1.csv")
q1v1 <- q1
#Passengers and fares for routes grouped by Origin, Destination, Operating Carrier and Fare Class
routes1 <- q1v1 %>% group_by(Origin, Destination, OperatingCarrier,FareClass) %>% summarise(TotalPassengers = sum(Passengers.x), MeanFPM = mean(FarePerMile))

routes1 <- routes1[routes1$TotalPassengers >=100,] #removing route combinations with less than 100 passengers 
routes1 <- routes1 %>% group_by(Origin, Destination, OperatingCarrier) %>% filter(n() == 2) #removing single fare class route combinations

q1v2 <- as.data.frame(semi_join(q1v1, routes1, by = c("Origin", "Destination", "OperatingCarrier", "FareClass"))) #full sample with only the filtered route combinations


```


*quantiles*

## getting quantiles


```{r}
# orig_dest_carr_q1

#get all the combos for origins, destinations, and operating carriers
q1v3 <- unique(q1v2[,c("Origin", "Destination", "OperatingCarrier")])
orig_dest_carr_q1 <- with(q1v3, q1v3[order(q1v3$Origin, q1v3$Destination), ])  #alphabetical order

#set the tracer
k=1

#Loop over all the combos to get the quantiles and cbind each subsequently
for (i in 1:nrow(orig_dest_carr_q1)){
  
  #initialise origin, destination, and carrier
  origin = orig_dest_carr_q1[i,1]
  destination = orig_dest_carr_q1[i,2]
  carrier = orig_dest_carr_q1[i,3]
  q1v4 <- q1v2 %>% filter(Origin == origin & Destination == destination & OperatingCarrier == carrier)
  if(k == 1){
    q1_final1 <- cbind(
      as.data.frame(quantile(q1v4[q1v4$FareClass == "Economy", ]$FarePerMile ,
                             probs=seq(0.001, 1, by=0.001),
                             na.rm=TRUE),
                    include.lowest=TRUE), 
      as.data.frame(quantile(q1v4[q1v4$FareClass == "Premium", ]$FarePerMile, 
                             probs=seq(0.001, 1, by=0.001),
                             na.rm=TRUE), include.lowest=TRUE),
      as.data.frame(quantile(q1v4$FarePerMile ,
                             probs=seq(0.001, 1, by=0.001), na.rm=TRUE),
                    include.lowest=TRUE))
    
    names(q1_final1)[1] <- paste(origin, destination, carrier, "E", sep = "_")
    names(q1_final1)[2] <- paste(origin, destination, carrier, "P", sep = "_")
    names(q1_final1)[3] <- paste(origin, destination, carrier, "All", sep = "_")
    k = k+1
    # x <-paste(i, j, m, "E", sep = "_")
  }
  else {
    
    q1_final2 <- cbind(
      as.data.frame(quantile(q1v4[q1v4$FareClass == "Economy", ]$FarePerMile ,
                             probs=seq(0.001, 1, by=0.001),
                             na.rm=TRUE),
                    include.lowest=TRUE), 
      as.data.frame(quantile(q1v4[q1v4$FareClass == "Premium", ]$FarePerMile, 
                             probs=seq(0.001, 1, by=0.001),
                             na.rm=TRUE), include.lowest=TRUE),
      as.data.frame(quantile(q1v4$FarePerMile ,
                             probs=seq(0.001, 1, by=0.001), na.rm=TRUE),
                    include.lowest=TRUE))
    
    names(q1_final2)[1] <- paste(origin, destination, carrier, "E", sep = "_")
    names(q1_final2)[2] <- paste(origin, destination, carrier, "P", sep = "_")
    names(q1_final2)[3] <- paste(origin, destination, carrier, "All", sep = "_")
    
    q1_final1 <- cbind(q1_final1,q1_final2)
    k=k+1
  }
  # paste(final)
  #for testing purposes
  # if (k ==4){
  # break
  # }
}

```


## mean values
```{r}
#set the tracer
j=1


#Loop over all the combos to get the means and cbind each subsequently
for (i in 1:nrow(orig_dest_carr_q1)){
  
  #initialise origin, destination, and carrier
  origin = orig_dest_carr_q1[i,1]
  destination = orig_dest_carr_q1[i,2]
  carrier = orig_dest_carr_q1[i,3]
  q1v5 <- q1v2 %>% filter(Origin == origin & Destination == destination & OperatingCarrier == carrier)
  if(j == 1){
    q1_final3 <- cbind(
      as.data.frame(mean(q1v5$FarePerMile[q1v5$FareClass == "Economy"])), 
      as.data.frame(mean(q1v5$FarePerMile[q1v5$FareClass == "Premium"])),
      as.data.frame(mean(q1v5$FarePerMile))
      )
    
    names(q1_final3)[1] <- paste(origin, destination, carrier, "E", sep = "_")
    names(q1_final3)[2] <- paste(origin, destination, carrier, "P", sep = "_")
    names(q1_final3)[3] <- paste(origin, destination, carrier, "All", sep = "_")
    j = j+1
    # x <-paste(i, j, m, "E", sep = "_")
  }
  else {
    
    q1_final4 <- cbind(
      as.data.frame(mean(q1v5$FarePerMile[q1v5$FareClass == "Economy"])), 
      as.data.frame(mean(q1v5$FarePerMile[q1v5$FareClass == "Premium"])),
      as.data.frame(mean(q1v5$FarePerMile))
      )
    
    names(q1_final4)[1] <- paste(origin, destination, carrier, "E", sep = "_")
    names(q1_final4)[2] <- paste(origin, destination, carrier, "P", sep = "_")
    names(q1_final4)[3] <- paste(origin, destination, carrier, "All", sep = "_")
    
    q1_final3 <- cbind(q1_final3,q1_final4)
    j=j+1
  }
  # paste(final)
  #for testing purposes
  # if (j ==4){
  # break
  # }
}

```


## combining the two tables and normalizing
```{r}

rownames(q1_final3) <- "mean"
q1v6 <- rbind(q1_final3, q1_final1)

library(stringr)
q1_norm <- q1v6 %>%
    summarise(across(everything(),
       ~ .[-1]/get(str_replace(cur_column(), '[^_]+$', 'All'))[1]))


q1_norm$percentile <- seq(0.001, 1, by=0.001) 
q1_norm$percentile <- sprintf("%1.2f%%", 100*q1_norm$percentile) 

q1_norm <- q1_norm %>%
  select(percentile, everything())

fwrite(q1_norm, file = "q1_Final_June2021.csv")

```

## END

```{r}
#qabc <- seq(0.0000, 1, by=0.001)
#qabc <- sprintf("%1.2f%%", 100*qabc)


#abc <- q1_final3
#rownames(abc) <- "mean"
#rm(abc)

#routes2 <- q1v2 %>% group_by(Origin, Destination, OperatingCarrier) %>% summarise(MeanFPM = mean(FarePerMile))
#routes2$CombinedCOl <- paste(routes2$Origin, routes2$Destination, routes2$OperatingCarrier, "All", sep = "_")
#routes3 <- subset(routes2, select = c("CombinedCOl", "MeanFPM"))
#routes4 <- as.data.frame(t(routes3))
#abc <- read.csv("sampl2.csv")
#names(abc)[1] <- "NYC_LAX_AA_E"

#abc %>%
    #summarise(across(everything(),
       #~ .[-1]/get(str_replace(cur_column(), '[^_]+$', 'All'))[1]))
```

